name = "QInsControlCore"
uuid = "cd9154b2-5d6d-4493-a0bc-3471f84f9c90"
authors = ["FaresX <fyzxst@sina.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
