name = "QInsControlCore"
uuid = "39cc742b-280f-4a36-a5f3-cc5e66799cee"
authors = ["FaresX <fyzxst@sina.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
